less/resources.less
Changed border colour styling for use in version 2 of the theme
=> CSS theme update

js/adapt-contrib-resourcesView.js, templates/resources.hbs
Enabled screen reader to read title and description
Enabled click on resource menu to take you to the first item (like with accordion)
=> Extended resources accessiblity

properties.schema
Not sure the description should be required?
=> Apply new elements to schema

templates/resources.hbs
=> Fix misplaced doublequote

js/adapt-contrib-resourcesView.js, templates/resources.hbs
https://adaptlearning.atlassian.net/browse/ABU-867
=> Added aria-label to indicate end of list.

templates/resources.hbs
Fixes https://adaptlearning.atlassian.net/browse/ABU-829
=> Prefix resource aria label with filter label

README.md, example.json, js/adapt-contrib-resources.js, properties.schema
Fixes https://github.com/adaptlearning/adapt_framework/issues/1001
Should be merge with https://github.com/adaptlearning/adapt_framework/pull/1005
=> implemented `_isEnabled` attribute

properties.schema
prep for multi-language support
=> add 'translatable' property

bower.json, properties.schema
Previously the asset filter was too restrictive.
=> Allows any type of asset to be selected in the authoring tool

README.md, bower.json, properties.schema
fixes https://github.com/adaptlearning/adapt_framework/issues/1437
=> add resourcesEnd to properties.schema

README.md, example.json, js/adapt-contrib-resources.js, properties.schema
This change is in anticipation of drawer item ordering support being added by adaptlearning/adapt_framework#1685
=> Issue-1393 - Support setting drawer item order

js/adapt-contrib-resourcesView.js
https://github.com/adaptlearning/adapt_framework/issues/1852
=> adapt-contrib-resources - iOS devices now opening resources in new tab

templates/resources.hbs
fixes https://github.com/adaptlearning/adapt_framework/issues/1706
=> improvements to word order in item ARIA

properties.schema
fixes https://github.com/adaptlearning/adapt_framework/issues/1698
=> add entry for itemAriaExternal

example.json, properties.schema, templates/resources.hbs
[#2166](https://github.com/adaptlearning/adapt_framework/issues/2166)
* Replaced text description with `role="link"`
List of outstanding PRs: https://github.com/adaptlearning/adapt_framework/issues/2206.
=> accessibility: issue/#2166 added role=link in place of text description

templates/resources.hbs
fixes https://github.com/adaptlearning/adapt_framework/issues/2378
=> don't escape the aria region label markup

README.md, example.json, js/adapt-contrib-resources.js, js/adapt-contrib-resourcesHelpers.js, js/adapt-contrib-resourcesView.js, less/resources.less, properties.schema, templates/resources.hbs
https://github.com/adaptlearning/adapt_framework/issues/1853
also addresses https://github.com/adaptlearning/adapt_framework/issues/2397
=> re-write of resources, as suggested in

bower.json, js/adapt-contrib-resourcesHelpers.js
Fixes https://github.com/adaptlearning/adapt_framework/issues/3012
Linted resourcesHelpers.js file and returned object
=> issue/3012 Missing export "default" 

README.md, bower.json, properties.schema
Resolves https://github.com/adaptlearning/adapt_framework/issues/3020.
=> Allow any type of asset

templates/resources.hbs
https://github.com/adaptlearning/adapt_framework/issues/3150
* Compile directive
=> issue/3150 Added compile directive

js/ResourcesHelpers.js, js/ResourcesView.js, js/adapt-contrib-resources.js
requires https://github.com/adaptlearning/adapt-contrib-core/pull/84
part of https://github.com/adaptlearning/adapt_framework/issues/2799
* Use `drawer`, `a11y` and `device` directly
* Linting issues
=> issue/2799 Removed redundant behaviour

js/ResourcesView.js, templates/resources.hbs
=> issue/71 - Adding tab structure to resources

schema/contentobject.schema.json
Fixes #87 
Updated schema $anchor value to reference Resources rather than PLP.
=> Fix: Update schema $anchor to reference resources (fixes #87)

schema/contentobject.schema.json
Fixes #97 
* Remove required title from contentobject schema (fixes #97)
[//]: # (List appropriate steps for testing if needed)
1. Create new course
2. Enable resources 
3. Create new page to check for errors 
[//]: # (Mention any other dependencies)
=> Fix: Remove required title from contentobject schema (fixes #97)

js/ResourcesView.js, templates/resources.jsx, templates/resourcesItem.jsx
* Adds event trigger for the purpose of tracking user selection of resources
* Solves for #106 
[//]: # (List appropriate steps for testing if needed)
1. Install this PR
2. Listen to event trigger of resources and ensure item data is pulling through.
[//]: # (Mention any other dependencies)
=> New: Add click event trigger (solves: #106)

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/issue_template.md
Fixes #124 
* Add new `issue_template.md` file with YAML frontmatter
* Add new `config.yml` file to disable blank template
=> Chore: Add support for new issue experience (fixes #124)

properties.schema
Fixes #131 
* Minor property title correction
=> Fix: Minor property title correction (issue/131)

bower.json, package-lock.json, package.json
#139 
Part of - https://github.com/adaptlearning/adapt_framework/issues/3698
* package updated to include semantic-release-replace-plugin for automated migration versioning (fixes #139)
=> Update: package updated to include semantic-release-replace-plugin for automated migration versioning (fixes #139)

test/e2e/menuResources.cy.js, test/e2e/pageResources.cy.js
Addresses #142 
* Putting force option on escape typing
=> Fix: Putting force option on escape typing

bower.json, less/resources.less, package.json
Fixes #130 
* Updates html target selector from element to `.html` class
=> Update: Update html target selector from element to class (fix #130)
