adaptlearning/adapt-contrib-resources

README.md
bower.json
example.json
js/adapt-contrib-resourcesView.js
properties.schema
templates/resources.hbs

See https://github.com/adaptlearning/adapt_framework/issues/1377
This change adds support for a new properties in resource items, which can be used to change the displayname of a document on download.
This feature should not break existing on future courses that do not define this attribute, and should fall back to the current behaviour.

Feature/file rename on download (issue #1377)

---

js/adapt-contrib-resourcesView.js

Apologies for the resurrection of this one, but turns out the nice jQuery version fails in Firefox. 
Happy to take further suggestions, though!

 - jQuery link download does not work in Firefox. Revert to plain JS.

---

js/adapt-contrib-resourcesView.js

when the user has installed an ActiveX control (such as Acrobat Reader DC) that will render PDFs in the browser

stop PDFs from opening in same window as course in IE

---

README.md
bower.json
example.json
js/adapt-contrib-resourcesView.js
properties.schema
templates/resources.hbs

#1643 - Added a forceDownload property to resourceItems which defaults to false, all items now open in a new window by default. This setting can be changed to download for individual resource items. Slight tweak to the code executed on click of a resource, it now looks for the forcedownload option, rather than forcing documents to be downloaded. Version bump

#1643 - Individual resources can now be set to download or open in new window 

---

properties.schema

fixes https://github.com/adaptlearning/adapt_framework/issues/1842
also improve help text for `_forceDownload` and `filename`

remove 'translatable' from _forceDownload

---

README.md
bower.json
js/adapt-contrib-resources.js

Since the core framework now takes care of managing the drawer removal it's no longer required to listen out for 'app:languageChanged'.

Resolves #1917, corrects issue with drawer and multi-language courses

---

properties.schema
templates/resources.hbs

[#2075](https://github.com/adaptlearning/adapt_framework/issues/2075)
* Removed unnecessary tab indexes
[#2150](https://github.com/adaptlearning/adapt_framework/issues/2150)
* Removed end label as not needed
* Added start label
General
* Switched to `a11y_aria_label` syntax
List of outstanding PRs: https://github.com/adaptlearning/adapt_framework/issues/2206.

accessibility: issue/#2075

---

templates/resources.hbs

fixes #82 
* Removes referenced tab title and description from aria-labels within each resource item. 
[//]: # (List appropriate steps for testing if needed)
Test with this branch!
[//]: # (Mention any other dependencies)

Fix: Labels for resources items are unnecessarily verbose (fixes #82)

---

example.json
js/ResourcesView.js
js/adapt-contrib-resources.js
properties.schema
schema/contentobject.schema.json
schema/course.schema.json
templates/resources.hbs

fixes #84
* Allow content object specific resources

New: Added contentObject specific resources (fixes #84)

---

templates/resources.jsx

Fixes #91 
* In onFilterClicked() in resources.jsx, removes 'this' from this.$(e.currentTarget).
* Removes `component__inner` class from `resources__inner`

Fix: Remove unnecessary 'this' from currentTarget (fixes #91)

---

README.md
example.json
js/ResourcesView.js
js/adapt-contrib-resources.js
properties.schema
schema/course.schema.json
templates/resources.jsx

Fixes: #99 
* Add support for header template use 
* Updated schemas to support new properties
* Updated documentation

Fix: Header template does not work (fixes #99)

---

example.json
js/ResourcesView.js
js/adapt-contrib-resources.js
less/resources.less
properties.schema
schema/course.schema.json
templates/resources.jsx

Fixes #103 
* Adds the ability for custom types
* When using more than the default 4 types, a class of `has-extra-types` is added
* Schema updates
1. Add custom categories according to _example.json_
2. Open the Resources drawer and behold the custom type buttons
Suggested changes to the Vanilla theme (will require a new ticket / PR):
1. Reduce font size and padding when using extra custom types.
```
.resources__filter.has-extra-types {
.resources__filter-btn {
font-size: 0.75rem;
padding: (@item-padding / 2) (@item-padding / 2);
}
}
```
2. Remove style that removes the border from the last item.
These screenshots show the maximum number of categories including the default ones.
With Vanilla changes to font size and padding:

Fix: Allow custom types (fixes #103)

---

README.md
example.json
js/ResourcesView.js
js/adapt-contrib-resources.js
properties.schema
schema/contentobject.schema.json
schema/course.schema.json
templates/resources.jsx
templates/resourcesFilterButton.jsx
templates/resourcesItem.jsx

Fix #115 
* Adds the new `_enableFilters` option to _course.json_ for hiding / showing filter buttons. Defaults to `true` for backwards compatibility. Filter buttons will also continue to be automatically hidden if all the item `_type` properties are the same.
* Update schemas, _example.json_ and _README.md_ with the new property
* Move some logic from the JSX into the JS (e.g. filter button column count).
* Update _README.md_: Include a bit about overriding some settings in _contentObjects.json_ since it was not explicitly stated. Also update the supported browser list.
In _course.json_ for the `_resources` object:
1. Test with `"_enableFilters": true`
2. Test with `"_enableFilters": false`
3. Test with no `"_enableFilters"` property
4. Test when all resource items have the same `_type` …

New: Add _enableFilters property (fixes #115)

---

js/adapt-contrib-resources.js

Fixes #117
* Replaces deprecated `drawer.triggerCustomView` with `drawer.openCustomView`

Fix: Replace deprecated drawer.triggerCustomView with drawer.openCustomView (fixes #117)

---

properties.schema
schema/course.schema.json

Fixes #120 
* Add all custom categories as valid `_type` values
1. Add a resource item with one of the 10 custom types. For example:
```
{
"_type": "custom1",
"title": "Adapt Project Site",
"description": "View the project's web site by clicking here.",
"_link": "https://www.adaptlearning.org/"
},
```
2. Upload course to the AAT.

Fix: Add all custom categories as valid _type values (fix #120)

---

migrations/v2.js
migrations/v3.js
migrations/v4.js
migrations/v5.js

#125 
* Migration scripts added to repo (fixes #125)

New: Migration scripts added to repo (fixes #125)

---

README.md
example.json

Fixes #128 
* Adds `_isGlobal` to _example.json_ and _README.md_

Chore: Add _isGlobal to example.json and README.md (fixes #128)

---

test/e2e/helpers.js
test/e2e/menuResources.cy.js
test/e2e/pageResources.cy.js

Fixes #134 
* Correcting tests to behave appropriately on courses with multiple drawer items

Fix: Correcting tests to behave appropriately on courses with multiple drawer items (issue/134)

---

test/e2e/menuResources.cy.js
test/e2e/pageResources.cy.js

Removed the check for aria-expanded on both menuResources and pageResources due to recent change to core drawer (https://github.com/adaptlearning/adapt-contrib-core/pull/663)
#137 
* e2e test updated to not check for aria-expanded (fixes #137)

Fix: e2e test updated to not check for aria-expanded (fixes #137)

---

test/e2e/helpers.js

Addresses #142 
* Added force option to resource drawer item click

Fix: Added force option to resource drawer item click
